## Test Connection
## Signup
### Register SME User
POST http://localhost:8080/api/signup
Content-Type: application/json

{
  "userType": "sme",
  "firstName": "Godwin",
  "lastName": "test",
  "email": "godwi6ntestingys@example.com",
  "password": "12345@test",
"confirmPassword": "12345@test",
  "phoneNumber": "+1234567890",
  "agreeTerms": true,
  "companyName": "TechSavvy Ltd",
  "companyType": "retail",
  "businessRegistration": "BR12345678"
}


### Login
POST http://localhost:8080/api/login
Content-Type: application/json

{
   "email": "godwintestingys@example.com",
  "password": "12345@test"
}
